apiVersion: configsync.gke.io/v1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/opowbow/config-sync-simple-ns # <=== REPLACE THIS WITH YOUR REPO URL
    branch: main
    dir: /
    auth: none                 # <=== REPLACE THIS WITH YOUR AUTH TYPE (e.g., none, ssh, token)
